### ISSUE TITLE
get babel error 

### ISSUE THREAD

**Issue by p-phillips** [JensErat/pandoc-scrlttr2#10]
Hi

I get the following error:
```
! Package babel Error: You haven't specified a language option.
See the babel package documentation for explanation.
```

I have tried setting lang to en and english in the YAML block but to no avail.

Any ideas ?
Pete

**Comment by JensErat** [comment]
Can you please provide an example markdown file and the versions of Pandoc and LaTeX distribution you're using?

**Comment by p-phillips** [comment]
Hi.

Content as per the example below.  
Pandoc version  1.15.0.6
Running Ubuntu 16.04, default texlive latex, 2015.20160320-1

Cheers
Pete

`---
letteroption:
- DIN          # typeset following DIN norm
- example      # loads example style file example.lco
to: |          # required, YAML multiline value
  Maurice Moss
  Reynholm Industries
  123 Carenden Road
  LONDON
  EC5M 8AJ
  GREAT BRITAIN
lang: english
subject: Lorem Ipsum
opening: Dear Moss,
closing: Sincerely,
...



Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim
veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea
commodo consequat. Duis aute irure dolor in reprehenderit in voluptate
velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint
occaecat cupidatat non proident, sunt in culpa qui officia deserunt
mollit anim id est laborum.
`

**Comment by nextlevelshit** [comment]
It should be 

```markdown
lang: en
```

**Comment by JensErat** [comment]
I must have missed the update on this issue -- thank you for replying @nextlevelshit.

Indeed, the `lang` parameter changed [as it did on the upstream pandoc project some time ago](http://pandoc.org/MANUAL.html#language-variables). The variable is not specific to this template at all.
