### ISSUE TITLE
Closing is centered instead of left aligned

### ISSUE THREAD

**Issue by nextlevelshit** [JensErat/pandoc-scrlttr2#11]
Inside the closing part the content is centered to the widest line. If my `closing` variable is the largest one, the other ones like `signature` are aligned centered to that one.

![latter-issue](https://user-images.githubusercontent.com/10194510/27795643-342518a2-6007-11e7-911a-bc7377131a87.png)

I cannot find the affected line of code for that. Is it maybe party of the used KOMA script?

**Comment by nextlevelshit** [comment]
Found a regarding issue of KOMA script: https://tex.stackexchange.com/questions/152535/strange-behaviour-of-closing-in-koma-script-scrlttr2-class

**Comment by JensErat** [comment]
The pandoc template does not modify scrlttr2's behavior here (in fact, it generally just wraps pandoc metadata to scrlttr2 variables). This seems to be an upstream issue (or rather seems somewhat expected, but surprising behavior); I'm closing the issue therefor.

If you want to apply the workaround described in the linked Q&A, I guess you should be able to put that into a letter option file (which is included in the letter's LaTeX headers).
